apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
